import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
    BrowserAnimationsModule, MatCheckboxModule, MatButtonModule, MatInputModule, MatAutocompleteModule, MatDatepickerModule,
    MatFormFieldModule, MatRadioModule, MatSelectModule, MatSliderModule, MatSlideToggleModule, MatMenuModule, MatSidenavModule,
    MatToolbarModule, MatListModule, MatGridListModule, MatCardModule, MatStepperModule, MatTabsModule, MatExpansionModule,
    MatButtonToggleModule, MatChipsModule, MatIconModule, MatProgressSpinnerModule, MatProgressBarModule, MatDialogModule,
    MatTooltipModule, MatSnackBarModule, MatTableModule, MatSortModule, MatPaginatorModule, MatTreeModule, MatNativeDateModule
    } from './index';
@NgModule ({
        imports:
        [
            CommonModule,
            BrowserAnimationsModule,
            MatCheckboxModule,
            MatButtonModule,
            MatInputModule,
            MatAutocompleteModule,
            MatDatepickerModule,
            MatFormFieldModule,
            MatRadioModule,
            MatSelectModule,
            MatSliderModule,
            MatSlideToggleModule,
            MatMenuModule,
            MatSidenavModule,
            MatToolbarModule,
            MatListModule,
            MatGridListModule,
            MatCardModule,
            MatStepperModule,
            MatTabsModule,
            MatExpansionModule,
            MatButtonToggleModule,
            MatChipsModule,
            MatIconModule,
            MatProgressSpinnerModule,
            MatProgressBarModule,
            MatDialogModule,
            MatTooltipModule,
            MatSnackBarModule,
            MatTableModule,
            MatSortModule,
            MatPaginatorModule,
            MatTreeModule,
            MatNativeDateModule
        ],
    exports:
        [
            BrowserAnimationsModule,
            MatCheckboxModule,
            MatButtonModule,
            MatInputModule,
            MatAutocompleteModule,
            MatDatepickerModule,
            MatFormFieldModule,
            MatRadioModule,
            MatSelectModule,
            MatSliderModule,
            MatSlideToggleModule,
            MatMenuModule,
            MatSidenavModule,
            MatToolbarModule,
            MatListModule,
            MatGridListModule,
            MatCardModule,
            MatStepperModule,
            MatTabsModule,
            MatExpansionModule,
            MatButtonToggleModule,
            MatChipsModule,
            MatIconModule,
            MatProgressSpinnerModule,
            MatProgressBarModule,
            MatDialogModule,
            MatTooltipModule,
            MatSnackBarModule,
            MatTableModule,
            MatSortModule,
            MatPaginatorModule,
            MatTreeModule,
            MatNativeDateModule
        ],
})
export class MaterialModule { }
